import type { Tool } from "./types";

/**
 * 全ツールの一覧（データ駆動）。
 *
 * status: "available"    -> Phase 1 で実際に動作する
 *         "coming-soon"  -> 仮ページ（準備中）
 * processor: 将来 BrowserProcessor / ServerProcessor のどちらを
 *            使うかの想定。"auto" はファイルサイズ等で自動切り替えする想定。
 */
export const tools: Tool[] = [
  // ------------------------------------------------------------------
  // 画像
  // ------------------------------------------------------------------
  {
    id: "image-resize",
    name: "画像リサイズ",
    category: "image",
    description: "画像の縦横サイズを指定してリサイズします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["resize", "サイズ変更", "縮小", "拡大"],
    featured: true,
  },
  {
    id: "image-compress",
    name: "画像圧縮",
    category: "image",
    description: "画質を保ちながら画像のファイルサイズを小さくします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["compress", "軽量化", "容量"],
    featured: true,
  },
  {
    id: "image-compress-to-size",
    name: "指定KBまで圧縮",
    category: "image",
    description: "目標のファイルサイズ(KB)を指定して自動で圧縮します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["kb", "容量指定", "圧縮"],
  },
  {
    id: "image-jpg-convert",
    name: "JPG変換",
    category: "image",
    description: "画像をJPG形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["jpg", "jpeg", "変換"],
  },
  {
    id: "image-png-convert",
    name: "PNG変換",
    category: "image",
    description: "画像をPNG形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["png", "変換", "透過"],
  },
  {
    id: "image-webp-convert",
    name: "WebP変換",
    category: "image",
    description: "画像をWebP形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["webp", "変換"],
  },
  {
    id: "image-sns-size",
    name: "SNSサイズ変換",
    category: "image",
    description: "Instagram・X(Twitter)など各SNSの推奨サイズに変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["sns", "instagram", "twitter", "x"],
  },
  {
    id: "image-crop",
    name: "画像トリミング",
    category: "image",
    description: "画像の必要な部分だけを切り抜きます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["crop", "切り抜き", "トリミング"],
  },
  {
    id: "image-batch-convert",
    name: "画像一括変換",
    category: "image",
    description: "複数の画像をまとめてJPG・PNG・WebPに変換し、ZIPでまとめてダウンロードします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["batch", "一括変換", "まとめて変換", "zip"],
  },
  {
    id: "image-rotate",
    name: "画像回転",
    category: "image",
    description: "画像を90度単位で回転・反転します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["rotate", "回転", "反転"],
  },
  {
    id: "image-flip",
    name: "画像反転",
    category: "image",
    description: "画像を左右または上下に反転します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["flip", "反転", "ミラー", "左右反転", "上下反転"],
  },
  {
    id: "image-grayscale",
    name: "画像グレースケール",
    category: "image",
    description: "画像をモノクロ・グレースケールに変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["grayscale", "モノクロ", "白黒", "グレースケール"],
  },
  {
    id: "image-adjust",
    name: "画像明るさ・コントラスト調整",
    category: "image",
    description: "画像の明るさとコントラストを調整します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["明るさ", "コントラスト", "brightness", "contrast", "調整"],
  },
  {
    id: "image-metadata-remove",
    name: "画像メタデータ削除",
    category: "image",
    description: "画像を再エンコードして不要なメタデータを取り除きます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["exif", "メタデータ", "位置情報", "撮影日時"],
  },
  {
    id: "image-watermark",
    name: "画像ウォーターマーク",
    category: "image",
    description: "画像にテキストの透かしを追加します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["透かし", "watermark", "ロゴ", "CONFIDENTIAL"],
  },

  // ------------------------------------------------------------------
  // PDF
  // ------------------------------------------------------------------
  {
    id: "pdf-merge",
    name: "PDF結合",
    category: "pdf",
    description: "複数のPDFファイルを1つに結合します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["merge", "結合"],
  },
  {
    id: "pdf-split",
    name: "PDF分割",
    category: "pdf",
    description: "PDFをページ単位で分割します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["split", "分割"],
  },
  {
    id: "pdf-delete-pages",
    name: "PDFページ削除",
    category: "pdf",
    description: "PDFの不要なページを削除します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["delete", "削除"],
  },
  {
    id: "pdf-reorder-pages",
    name: "PDFページ並び替え",
    category: "pdf",
    description: "PDFのページ順序を並び替えます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["reorder", "並び替え"],
  },
  {
    id: "pdf-rotate",
    name: "PDF回転",
    category: "pdf",
    description: "PDFのページを回転します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["rotate", "回転"],
  },
  {
    id: "pdf-compress",
    name: "PDF圧縮",
    category: "pdf",
    description: "PDFのファイルサイズを圧縮します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["compress", "軽量化"],
  },
  {
    id: "pdf-to-image",
    name: "PDF→画像",
    category: "pdf",
    description: "PDFの各ページを画像として書き出します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["image", "画像化"],
  },
  {
    id: "image-to-pdf",
    name: "画像→PDF",
    category: "pdf",
    description: "複数の画像を1つのPDFにまとめます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["pdf化"],
  },
  {
    id: "pdf-to-text",
    name: "PDF→テキスト",
    category: "pdf",
    description: "PDFからテキストを抽出します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["text", "抽出", "テキスト化"],
  },
  {
    id: "pdf-to-excel",
    name: "PDF→Excel",
    category: "pdf",
    description: "PDF内の表をExcelファイルに変換します",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["excel", "表"],
  },
  {
    id: "pdf-to-word",
    name: "PDF→Word",
    category: "pdf",
    description: "PDFをWord文書に変換します",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["word", "文書"],
  },
  {
    id: "ocr",
    name: "OCR",
    category: "pdf",
    description: "画像やスキャンしたPDFから文字を読み取ります",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["文字認識", "スキャン", "OCR"],
  },
  {
    id: "pdf-extract-pages",
    name: "PDFページ抽出",
    category: "pdf",
    description: "指定したページだけを新しいPDFとして取り出します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["extract", "抽出", "ページ抽出"],
  },
  {
    id: "pdf-add-page-numbers",
    name: "PDFページ番号追加",
    category: "pdf",
    description: "PDFの各ページにページ番号を追加します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["ページ番号", "page number", "ノンブル"],
  },
  {
    id: "pdf-watermark",
    name: "PDF透かし",
    category: "pdf",
    description: "PDFの各ページにテキストの透かしを追加します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["透かし", "watermark", "社外秘", "CONFIDENTIAL"],
  },
  {
    // Phase 6で検討したが、現在の依存ライブラリ(pdf-lib)はPDFの暗号化(パスワード保護)の
    // 書き込みを公式にサポートしておらず(README「Encryption Handling」参照)、
    // 代替ライブラリも(a)出所不明で信頼できない、(b)単一メンテナのWASMラッパーで
    // バンドルサイズが大きい、(c)AGPLライセンスで商用利用と非互換、という理由で
    // いずれも採用を見送った。「見た目だけのパスワード入力欄」を作ることを避けるため、
    // このツールは今回 available にしない（最終報告を参照）。
    id: "pdf-password-protect",
    name: "PDFパスワード保護",
    category: "pdf",
    description: "PDFにパスワードを設定して保護します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["password", "パスワード", "暗号化", "保護"],
  },
  {
    id: "pdf-resize-pages",
    name: "PDFページサイズ変更",
    category: "pdf",
    description: "PDFのページサイズをA4・A3・Letterなどに変更します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["ページサイズ", "a4", "a3", "letter", "リサイズ"],
  },
  {
    id: "pdf-metadata-remove",
    name: "PDFメタデータ削除",
    category: "pdf",
    description: "PDFのタイトル・作成者などのメタデータを確認して削除します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["メタデータ", "プロパティ", "作成者", "タイトル削除"],
  },
  {
    id: "pdf-crop-pages",
    name: "PDF余白調整",
    category: "pdf",
    description: "PDFページの上下左右の余白（表示範囲）を調整します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["余白", "クロップ", "crop", "トリミング"],
  },

  // ------------------------------------------------------------------
  // ファイル
  // ------------------------------------------------------------------
  {
    id: "file-bulk-rename",
    name: "一括ファイル名変更",
    category: "file",
    description: "複数のファイル名をまとめて変更します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["rename", "リネーム"],
  },
  {
    id: "file-sequential-rename",
    name: "連番リネーム",
    category: "file",
    description: "ファイル名に連番を付けてリネームします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["連番", "リネーム"],
  },
  {
    id: "file-zip",
    name: "ZIP作成",
    category: "file",
    description: "複数のファイルをまとめてZIP化します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["zip", "圧縮"],
  },
  {
    id: "file-unzip",
    name: "ZIP解凍",
    category: "file",
    description: "ZIPファイルをブラウザ上で解凍して中身を取り出します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["zip", "解凍", "展開", "unzip"],
  },
  {
    id: "file-hash",
    name: "ファイルハッシュ",
    category: "file",
    description: "ファイルのSHA-256ハッシュ値を計算します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["hash", "ハッシュ", "sha256", "sha-256", "checksum"],
  },
  {
    id: "file-inspector",
    name: "ファイル情報確認",
    category: "file",
    description: "ファイル名・種類・サイズなどの基本情報を確認します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["ファイル情報", "メタ情報", "プロパティ"],
  },

  // ------------------------------------------------------------------
  // CSV・Excel
  // ------------------------------------------------------------------
  {
    id: "csv-format",
    name: "CSV整形",
    category: "csv-excel",
    description: "余分な空白・空行・改行コードを整えます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["csv", "整形", "クリーニング"],
    featured: true,
  },
  {
    id: "csv-to-excel",
    name: "CSV→Excel",
    category: "csv-excel",
    description: "CSVファイルをExcel形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["excel", "変換"],
  },
  {
    id: "excel-to-csv",
    name: "Excel→CSV",
    category: "csv-excel",
    description: "ExcelファイルをCSV形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["csv", "変換"],
  },
  {
    id: "csv-merge",
    name: "CSV結合",
    category: "csv-excel",
    description: "複数のCSVファイルを1つに結合します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["結合", "マージ"],
  },
  {
    id: "csv-dedupe",
    name: "重複削除",
    category: "csv-excel",
    description: "CSVの重複した行を削除します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["重複", "削除"],
  },
  {
    id: "csv-to-json",
    name: "CSV→JSON",
    category: "csv-excel",
    description: "CSVファイルをJSON形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["json", "変換", "csv to json"],
  },
  {
    id: "json-to-csv",
    name: "JSON→CSV",
    category: "csv-excel",
    description: "JSON配列をCSV形式に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["json", "csv", "変換", "json to csv"],
  },
  {
    id: "csv-replace",
    name: "文字列置換",
    category: "csv-excel",
    description: "CSV内の文字列を一括置換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["置換", "検索"],
  },
  {
    id: "csv-column-editor",
    name: "CSV列編集",
    category: "csv-excel",
    description: "CSVの列を選択・削除・リネーム・並び替えします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["列編集", "列削除", "列並び替え", "column"],
  },

  // ------------------------------------------------------------------
  // 学生向け
  // ------------------------------------------------------------------
  {
    id: "pomodoro-timer",
    name: "ポモドーロタイマー",
    category: "student",
    description: "集中と休憩を繰り返す勉強・作業用タイマーです",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["timer", "タイマー", "勉強", "集中"],
    featured: true,
  },
  {
    id: "unit-converter",
    name: "単位変換",
    category: "student",
    description: "長さ・重さ・温度などの単位を変換します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["単位", "換算"],
  },
  {
    id: "citation-formatter",
    name: "参考文献リスト整形",
    category: "student",
    description: "レポート用の参考文献リストを整形します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["レポート", "引用"],
  },

  // ------------------------------------------------------------------
  // 仕事
  // ------------------------------------------------------------------
  {
    id: "business-card-qr",
    name: "名刺QRコード作成",
    category: "work",
    description: "連絡先情報をQRコード化して名刺やメールに使えます",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["qr", "名刺", "連絡先", "vcard"],
    featured: true,
  },
  {
    id: "meeting-notes-template",
    name: "議事録テンプレート生成",
    category: "work",
    description: "会議の議事録テンプレートを自動生成します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["議事録", "会議"],
  },
  {
    id: "estimate-generator",
    name: "見積書作成",
    category: "work",
    description: "オンラインで見積書を作成してPDFで保存できます",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["見積書", "estimate", "帳票"],
  },
  {
    id: "invoice-generator",
    name: "請求書作成",
    category: "work",
    description: "請求書を作成して振込先情報付きのPDFでダウンロードできます",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["請求書", "invoice", "帳票"],
    featured: true,
  },
  {
    id: "order-generator",
    name: "注文書作成",
    category: "work",
    description: "注文書を簡単に作成してPDFで保存できます",
    status: "available",
    requiredPlan: "premium",
    processor: "browser",
    keywords: ["注文書", "order", "発注", "帳票"],
  },

  // ------------------------------------------------------------------
  // クリエイター
  // ------------------------------------------------------------------
  {
    id: "color-palette-generator",
    name: "配色パレット生成",
    category: "creator",
    description: "ベースカラーから調和の取れた配色パレットを作成します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["color", "配色", "パレット", "デザイン"],
    featured: true,
  },
  {
    id: "gradient-generator",
    name: "グラデーション生成",
    category: "creator",
    description: "CSS用のグラデーションを作成します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["gradient", "css"],
  },
  {
    id: "background-remover",
    name: "背景透過（背景除去）",
    category: "creator",
    description: "AIを使って画像の背景を自動的に除去します",
    status: "coming-soon",
    requiredPlan: "standard",
    processor: "server",
    keywords: ["背景除去", "透過", "ai"],
  },

  // ------------------------------------------------------------------
  // その他
  // ------------------------------------------------------------------
  {
    id: "qr-generator",
    name: "QRコード生成",
    category: "other",
    description: "URLやテキストからQRコードを作成します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["qr", "コード"],
    featured: true,
  },
  {
    id: "password-generator",
    name: "パスワード生成",
    category: "other",
    description: "安全でランダムなパスワードを生成します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["password", "パスワード", "乱数"],
    featured: true,
  },
  {
    id: "char-count",
    name: "文字数カウント",
    category: "other",
    description: "文字数・単語数・行数をカウントします",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["文字数", "カウント"],
  },
  {
    id: "json-formatter",
    name: "JSON整形",
    category: "other",
    description: "JSONを見やすく整形・検証します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["json", "整形", "フォーマット"],
  },
  {
    id: "text-line-cleaner",
    name: "テキスト行整理",
    category: "other",
    description: "空行削除・重複行削除・並び替えなどをまとめて行います",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["テキスト", "整理", "重複削除", "ソート", "空行削除"],
  },
  {
    id: "text-case-converter",
    name: "大文字・小文字変換",
    category: "other",
    description: "英字テキストを大文字・小文字・先頭大文字に変換します",
    status: "available",
    requiredPlan: "standard",
    processor: "browser",
    keywords: ["大文字", "小文字", "uppercase", "lowercase", "case"],
  },
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.featured);
}
